default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  adapter: mysql2
  database: dyscalculia_dev
  host: localhost
  min_messages: warning
  pool: 5
  host: 127.0.0.1
  username: root
  password: waqar123
  timeout: 5000
  encoding: utf8

test:
  adapter: mysql2
  database: dyscalculia_test
  host: localhost
  min_messages: warning
  pool: 5
  host: 127.0.0.1
  username: root
  password: waqar123
  timeout: 5000
  encoding: utf8